rainbow: debug / log config
sgadrat/fceux pull request #14
Opened 2020-07-03 20:15 UTC by BrokeStudio

basic debug configuration implemented

* Added two commands: DEBUG_GET_CONFIG and DEBUG_SET_CONFIG
* Added one return command: DEBUG_CONFIG

* if debug_config & 1 == 1 DEBUG_LOG command will output data in message log window
* debug_config does more things on hardware that we don't need to implement in the emulator

2020-07-03 23:03 UTC, sgadrat requested changes

2020-07-03 23:03 UTC, sgadrat commented on src/boards/rainbow_esp.cpp
> +				static_cast<uint8>(debug_config)
`this->debug_config`

2020-07-03 23:03 UTC, sgadrat commented on src/boards/rainbow_esp.cpp
> +				debug_config = this->rx_buffer.at(2);
`this->debug_config`

2020-07-03 23:03 UTC, sgadrat commented on src/boards/rainbow_esp.cpp
> +				if (debug_config & 1 == 1) {
`this->debug_config`

2020-07-03 23:03 UTC, sgadrat commented on src/boards/rainbow_esp.cpp
> +				mg_printf(nc, "{\"debugConfig\":\"%i\"}", self->debug_config);
Don't know enough of mongoose, I may be wrong and you can just close the comment.

If `mg_printf` is allows full `printf` syntax, it should be `%u` as `debug_config` is unsigned. (even if it make actually no difference in this case)

Side note: `%d` is more common than `%i`. (I actually searched because I thought `%i` was deprecated... it is not, just rarely used.)

2020-07-04 07:05 UTC, BrokeStudio commented on src/boards/rainbow_esp.cpp
> +				mg_printf(nc, "{\"debugConfig\":\"%i\"}", self->debug_config);
It was initially `%d` but didn't work (the issue was elsewhere of course) that's why I switched to `%i`.
Anyway, I'll change it to `%u`.

2020-07-04 12:40 UTC, sgadrat approved these changes

2020-07-04 12:40 UTC, merged